# -*- coding: utf-8 -*-
"""model

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RqdKyC6XMHohnsF8xKsFeRD6vUq55HKN
"""

print('Hello World')